title = "Maite Clausell's Website"
baseURL = "https://dev.maiteclausell.com/"
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"
  homeUrl = "/"
  language = "Language"
  PortfolioName = "Back to Portfolio"
  PortfolioUrl = "work"

  [params.slider]
    enable = true
    title = "A digital marketing &amp; design agency"
    subtitle = "We love the Web and the work we do.<br/>We work closely with our clients to deliver the best possible solutions for their needs"

  [params.wrapper]
    enable = true
    title = "About me"
    paragraph1 = """In 2013 I graduated in English Philology and moved to London (England) to study an MA in Audiovisual Translation. After finishing my MA in 2014, I decided to stay in England, though I was born and raised near the Mediterranean Sea in Spain. In the years I have lived in England, I have moved around and lived in different places: London, Cambridge and Surrey, to move back to London."""
		paragraph2 = """In 2017 I finished an MA in Translation and New Technologies: Translation of Software and Multimedia Products and worked at the translation team of a marketing company as Spanish Language Lead. Since the beginning of 2018, I am working as a freelance translator, subtitler and localiser and as a videogame QA Tester and proofreader at Pole to Win. In my free time I like to read, knit, play video games and create subtitles for a Spanish web series."""

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = false
    title = "We believe in great ideas"
    content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    [[languages.en.menu.header]]
      weight = 2
      name = "Portfolio"
      url = "/work"
    [[languages.en.menu.header]]
      weight = 3
      name = "Blog"
      url = "/blog"
    [[languages.en.menu.header]]
      weight = 4
      name = "Services"
      url = "/service"

    [[languages.en.menu.footer]]
      weight = 1
      name = "About me"
      url = "#"
    [[languages.en.menu.footer]]
      weight = 2
      name = "Contact us"
      url = "#"
    [[languages.en.menu.footer]]
      weight = 3
      name = "How it works"
      url = "#"
    [[languages.en.menu.footer]]
      weight = 4
      name = "Blog"
      url = "#"
    [[languages.en.menu.footer]]
      weight = 5
      name = "Terms"
      url = "#"

  [languages.es]
    languageName = "Spanish"
    weight = 2
    contentDir = "content/es"
    [languages.es.params]
      home = "Inicio"
      homeUrl = "/es"
      PortfolioName = "Volver al porfolio"
      PortfolioUrl = "es/work"
    [[languages.es.menu.header]]
      weight = 2
      name = "Porfolio"
      url = "/es/work"
    [[languages.es.menu.header]]
      weight = 3
      name = "Blog"
      url = "/es/blog"
    [[languages.es.menu.header]]
      weight = 4
      name = "Servicios"
      url = "/es/service"

    [[languages.es.menu.footer]]
      weight = 1
      name = "About us"
      url = "#"
    [[languages.es.menu.footer]]
      weight = 2
      name = "Contact us"
      url = "#"
    [[languages.es.menu.footer]]
      weight = 3
      name = "How it works"
      url = "#"
    [[languages.es.menu.footer]]
      weight = 4
      name = "Blog"
      url = "#"
    [[languages.es.menu.footer]]
      weight = 5
      name = "Terms"
      url = "#"

  [languages.ca]
    languageName = "Catalan"
    weight = 3
    contentDir = "content/ca"
    [languages.ca.params]
      home = "Inici"
      homeUrl = "/ca"
      PortfolioName = "Tornar al portfolio"
      PortfolioUrl = "ca/work"
    [[languages.ca.menu.header]]
      weight = 2
      name = "Dossier"
      url = "/ca/work"
    [[languages.ca.menu.header]]
      weight = 3
      name = "Blog"
      url = "/ca/blog"
    [[languages.ca.menu.header]]
      weight = 4
      name = "Serveis"
      url = "/ca/service"

    [[languages.ca.menu.footer]]
      weight = 1
      name = "About us"
      url = "#"
    [[languages.ca.menu.footer]]
      weight = 2
      name = "Contact us"
      url = "#"
    [[languages.ca.menu.footer]]
      weight = 3
      name = "How it works"
      url = "#"
    [[languages.ca.menu.footer]]
      weight = 4
      name = "Blog"
      url = "#"
    [[languages.ca.menu.footer]]
      weight = 5
      name = "Terms"
      url = "#"
