title = "Maite Clausell's Website"
baseURL = "https://dev.maiteclausell.com/"
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"
  homeUrl = "/"
  language = "Language"
  PortfolioName = "Back to Portfolio"
  PortfolioUrl = "work"
  BlogName = "Back to Blog"
  BlogUrl= "blog"

  [params.slider]
    enable = true
    title = "Maite Clausell"
    subtitle = "Translator - Subtitler - Localiser"

  [params.wrapper]
    enable = true
    title = "About me"
    paragraph1 = """In 2013 I graduated in English Philology and moved to London (England) to study an MA in Audiovisual Translation. After finishing my MA in 2014, I decided to stay in England, though I was born and raised near the Mediterranean Sea in Spain. In the years I have lived in England, I have moved around and lived in different places: London, Cambridge and Surrey, to move back to London."""
		paragraph2 = """In 2017 I finished an MA in Translation and New Technologies: Translation of Software and Multimedia Products and worked at the translation team of a marketing company as Spanish Language Lead. Since the beginning of 2018, I am working as a freelance translator, subtitler and localiser and as a videogame QA Tester and proofreader at Pole to Win. In my free time I like to read, knit, play video games and create subtitles for a Spanish web series."""

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = false
    title = "We believe in great ideas"
    content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    title = "Contact me"

  [params.associations]
    enable = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    [[languages.en.menu.header]]
      weight = 2
      name = "Portfolio"
      url = "/work"
    [[languages.en.menu.header]]
      weight = 3
      name = "Blog"
      url = "/blog"
    [[languages.en.menu.header]]
      weight = 4
      name = "Services"
      url = "/service"

  [languages.es]
    languageName = "Spanish"
    weight = 2
    contentDir = "content/es"
    [languages.es.params]
      home = "Inicio"
      homeUrl = "/es"
      PortfolioName = "Volver al porfolio"
      PortfolioUrl = "es/work"
      BlogName = "Volver al blog"
      BlogUrl= "es/blog"
    [[languages.es.menu.header]]
      weight = 2
      name = "Porfolio"
      url = "/es/work"
    [[languages.es.menu.header]]
      weight = 3
      name = "Blog"
      url = "/es/blog"
    [[languages.es.menu.header]]
      weight = 4
      name = "Servicios"
      url = "/es/service"

  [languages.ca]
    languageName = "Catalan"
    weight = 3
    contentDir = "content/ca"
    [languages.ca.params]
      home = "Inici"
      homeUrl = "/ca"
      PortfolioName = "Tornar al portfolio"
      PortfolioUrl = "ca/work"
      BlogName = "Tornar al blog"
      BlogUrl= "ca/blog"
    [[languages.ca.menu.header]]
      weight = 2
      name = "Dossier"
      url = "/ca/work"
    [[languages.ca.menu.header]]
      weight = 3
      name = "Blog"
      url = "/ca/blog"
    [[languages.ca.menu.header]]
      weight = 4
      name = "Serveis"
      url = "/ca/service"

